javaweb:
  image: 192.168.10.118:5000/our/webjava:v2
  tty: true
  stdin_open: true
#  ports:
#    - "8080"
LB-javaweb:
  ports: "8080"
  image: rancher/load-balancer-service
  tty: true
  links:
  - javaweb:javaweb
  stdin_open: true
