.catalog:
  name: javaweb-cluster
  version: 1.0.0
  description: |
    JAVA_WEB
  uuid: javaweb-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: "scale"
      description: "how many tomcats you need"
      label: "numbers of tomcat"
      required: true
      default: 1
      type: "int"
    - variable: "volumes"
      description: "the dir for pull data"
      label: "your dir"
      required: true
#      default: none
      type: "string"
    - variable: "cpu"
      description: "how many cpus you need"
      label: "numbers of cpu"
      required: true
      default: 1
      type: "int"
    - variable: "mem"
      description: "how many mems you need"
      label: "numbers of mem"
      required: true
      default: 2147483648
      type: "int"
javaweb:
  scale: ${scale}
LB-javaweb:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
