.catalog:
  name: javaweb-cluster
  version: 1.0.0
  description: |
    JAVA_WEB
  uuid: javaweb-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: "scale"
      description: "number of tomcat"
      label: "tomcat numbers"
      required: true
      default: 1
      type: "int"
javaweb:
  scale: ${scale}
LB-javaweb:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
